name: E2E

on:
  - pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm, cypress, contentlayer, & next.js cache
        with:
          path: |
            ~/.cache/Cypress
            .next
            .contentlayer
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Contentlayer build
        run: pnpm contentlayer build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: pnpm i --frozen-lockfile
          wait-on: 'http://localhost:3001'
          start: pnpm dev
