name: Unit Tests

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: package-lock.json
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm i --frozen-lockfile
      - run: pnpm test:unit:ci
