name: Unit Tests

permissions:
  contents: read
  pull-requests: write

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # required by coverage reporter.
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0 # match package.json:packageManager version.
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm test:unit:ci
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
