name: Type Check

on:
  - pull_request

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: bun install
      - run: bun contentlayer build
      - run: bun type-check
